### ISSUE TITLE
noUiSlider not working in Shadow DOM

### ISSUE THREAD

**Issue by carlosescri** [leongersen/noUiSlider#1035]
Hi again @leongersen.

I'm trying to make the slider work inside a web component with [LitElement](https://lit-element.polymer-project.org/).

Seems that the slider doesn't work when put in the shadow DOM, but it works when it's in the light DOM (losing all benefits of encapsulation).

You can see a demo here (notice I'm using a global noUISlider instead of a bundled one for simplicity):

https://stackblitz.com/edit/lit-element-my-range

The slider relies on internal styles, instantiates properly but has no handles

If you edit the `my-range.ts` file and uncomment the `createRenderRoot()` function to make the component contents render in the light DOM, you will see that the slider works again (it relies in the global styles in the page).

I tried to guess why it doesn't work but I'm afraid I don't know too much about noUiSlider internals yet.

**Comment by leongersen** [comment]
I took me a while to figure out what's happening here, but the noUiSlider stylesheet expects to be in an `<html>` node (to determine if the document is ltr or rtl). 

https://github.com/leongersen/noUiSlider/blob/master/src/nouislider.core.less

As a workaround, you could add the two declarations starting with `html:not([dir="rtl"])` to your shadow root, but ideally this gets fixed in the stylesheet.

**Comment by leongersen** [comment]
This is fixed in noUiSlider 14.1.0. Thanks for reporting, @carlosescri!

**Comment by carlosescri** [comment]
Thanks @leongersen ! Nice solution 👍
