### ISSUE TITLE
Lifting while dragging on iOS results in handle returning to original position?

### ISSUE THREAD

**Issue by brandoncc** [leongersen/noUiSlider#1057]
We are experiencing issues on iOS where the handle returns to its original position if you lift your finger while dragging. I was able to replicate the issue on the example website, so I don't think it is code specific to our app. Is there a way to stop this from happening?

![ios slider issues](https://user-images.githubusercontent.com/543973/75620624-b8d11980-5b3f-11ea-99fc-fc5020372588.gif)

**Comment by leongersen** [comment]
I saw this issue, but I haven't gotten around to testing it myself yet, since I don't have an iPhone on hand. I should be able to have a look somewhere this week. Does this happen on iPad too?

**Comment by brandoncc** [comment]
It was tough to replicate again for some reason, but I was finally able to do it on a fairly consistent basis. [Here is a video](https://dl.dropboxusercontent.com/s/lzdo919x57u2lzq/nouislider%20on%20ipad.mp4) of me doing it on an iPad. As you can see, it is not as consistent as the iPhone, but still present.

**Comment by brandoncc** [comment]
I found that we had an issue with react hooks that were exacerbating the issue, and once I fixed that our application is okay now. The issue still exists for some reason on iOS (as shown in the video/gif), but I don't know if it is still something you need to chase down.

If the issue returns full force for us, I will respond here. Thanks!

**Comment by navoshta** [comment]
I am currently working on embedding [ipywidgets](https://github.com/jupyter-widgets/ipywidgets) into my [iOS app](https://juno.sh/), and it uses noUiSlider under the hood. Unfortunately, this issue somewhat ruins the experience, and indeed can be consistently reproduced on example website using both iOS and iPadOS. I managed to patch it, so that it works well in my app — so I thought I'd share my findings in case this helps addressing the underlying issue.

So, looks like `eventTap(event)` callback receives an erroneous event _after_ user stops interacting with the slider, which triggers an extra slide-update-change-set sequence of events. Although I didn't investigate much further and can't tell where this event originates, Safari JS Console identifies it as `MouseEvent` (even on touch-only devices). Although iOS can, in fact, receive `MouseEvent`s when trackpad is connected to an iPad, this particular event doesn't look legit anyway, as it doesn't even have `buttons` property set, for instance. 

In case it's going to be helpful: my patch simply checks if `event` in `eventTap(event)` has either `buttons` or `touches`, otherwise assumes it's an erroneous event and returns early:

```js
function eventTap(event) {
    if (!event.buttons && !event.touches) {
        return false;
    }
    ...
}
```

This may not be the most optimal workaround, but please bear in mind that I'm not a web developer and have very little experience with JS. Also, as you can imagine, I don't need to worry about too many browsers/platforms in my particular case! 😁 I do hope this helps fixing the actual underlying issue though.

**Comment by leongersen** [comment]
@navoshta Thanks for adding your finding to this. I think the check for `buttons` on any mouse-related event makes sense. Would you be able to create a PR with this fix?

**Comment by navoshta** [comment]
Sure @leongersen — I've linked PR to this issue, feel free to change whatever you think is necessary.

**Comment by leongersen** [comment]
I've just tested and merged the fix provided by @navoshta. Thanks for contributing on this issue, everybody!
