### ISSUE TITLE
Question: Broken line and labels at stops?

### ISSUE THREAD

**Issue by svdtz** [leongersen/noUiSlider#1185]
We are trying to build the following:

<img width="500" src="https://user-images.githubusercontent.com/60693612/156383191-8e10c8b9-f31e-47ff-8722-3e9fd1e62e69.png">

It seems we can get the restyling and colors, but the PIPS don't quite seem to work for us. 
Is there any advice to get:
- a broken line with stops
- labels at those stops

Any advice is welcomed

Thx a lot

**Comment by leongersen** [comment]
Sorry, I forgot to respond to this. This type of design isn't super easy to realize within noUiSlider, as it uses transforms to scale the connecting element between the handles. 

Best bet is using the pips feature for the labels and moving `.noUi-pips` into `.noUi-base` (because of z-indexing). See #1179. You can style the pips to be white, and set the z-index between `.noUi-connect` and `.noUi-origin`.
