### ISSUE TITLE
noUiSlider and Input type="number"

### ISSUE THREAD

**Issue by RomeoBy** [leongersen/noUiSlider#1191]
Hey! Cool slider! I don't understand why it doesn't work for me? I set the slider to input type="number" ([https://refreshless.com/nouislider/examples/#section-html5](https://refreshless.com/nouislider/examples/#section-html5)) but nothing happens when moving. If you manually change the values ​​- then everything works.

Here is an example: [Link](https://audiotuner.net/index/oscillator_demo/0-18)

What am I doing wrong?

**Comment by leongersen** [comment]
You're talking about the "frequency" label not updating when moving the slider?

![image](https://user-images.githubusercontent.com/1206361/163547069-614bd8d0-f307-4eb1-9781-c1e39c90491b.png)

I don't work with Vue myself, but I'm assuming you'll either need to update `carrier.freq` instead of `freqInput.value` in your `update` event handler to keep your model in sync.

**Comment by RomeoBy** [comment]
No, the label frequency it doesn't matter. I want the frequency value in the input to change when the slider moves. The value itself changes, but the frequency does not change. If you manually enter numbers in the input, then the frequency changes normally and the slider moves. I don't know how to do it, noUiSlider seems to change the value in the input, but the frequency doesn't change...

**Comment by leongersen** [comment]
Your example broke (which is why is prefer code posted in issues over external links!), but i'll refer you to my previous comment: this is something you need to solve in your Vue model.
