### ISSUE TITLE
Min = max

### ISSUE THREAD

**Issue by mgibbs189** [leongersen/noUiSlider#236]
I know this is an edge case - I'm using noUiSlider as a filter on a product listing (think Amazon). The [min] and [max] are based dynamically on the result set.

When the result set is filtered to a single item, [min] and [max] are the same, and the slider behaves oddly (it's supposed to be a 2-handle slider):

![ss1](http://i.imgur.com/opx0GF8.png)

There's some error handling I could add on my side, but I'm wondering if it's worth building this edge-case into noUiSlider itself? E.g. something like

![ss2](http://i.imgur.com/OVQc1Ky.png)

**Comment by no-gravity** [comment]
I have this problem too. The NaN-NaN in the input fields is definitely a bug, can we agree on this?

As for slider positions when min=max I would find it most natural to have the min slider sits on the left and the max slider sits on the right.

**Comment by leongersen** [comment]
> is definitely a bug

Yes, but: no. I'm considering setting `min` and `max` to the same value a *serious* UI bug, as no user is going to understand what an unmovable slider means. 'Resolving' this issue by throwing an error on `min = max` would be an option, but the amount of response here seems to indicate something else is required. What other user-friendly options can we come up with?

**Comment by no-gravity** [comment]
I have to say that I only encountered this with test data, so it is a low priority issue for me. I love how elegant no ui slider is. That's why I'm inclined to join this discussion in the hope that it helps on the way to perfection :)

I strongly feel that raising an error would be a bad idea. And that handling min=max just like any other combination of values is the right approach.

Imagine the following: A user selects "Show me all animals in Africa that weight more then 5kg and live on trees". Then the filters on the animal page might look like this:

Live span in years: 3 - 15
Nr of legs: 4 - 4
Run speed in km/h: 3 - 22

So he immediately sees that heavy tree animals in Africa all have 4 legs. That's exactly what he expects. Any change in the UI would be confusing. Let alone getting an error.

**Comment by leongersen** [comment]
Sounds fair. I might argue it *could* be better to show `all animals in the current selection have N legs`, but that has obviously nothing to do with noUiSlider. I'm also fairly sure that for two-handle sliders `min=max` should put both handles on the same position.

**Comment by jmoulin-vp** [comment]
Hello, I have the same NaN problem.
will this bug be fixed ?

**Comment by jmoulin-vp** [comment]
My min and max values are dynamic, so for the moment, my solution is :

```JAVASCRIPT
if (min == max) {
	minRange -= 60; // minus 1 minute
	maxRange += 60; // plus 1 minute
	step = 60; // 1 minute step
}
$('#slider').noUiSlider({
	start: [min, max],
	step: step,
	range: {
		'min': minRange,
		'max': maxRange
	}
}, true);
if (min == max) {
	$slider.attr('disabled',' disabled');
}
```

So the spots will be on the middle of the slider, disabled

**Comment by cedricjimenez** [comment]
Is it accidental again ? :smiley:

**Comment by kiaplayer** [comment]
@jmoulin-vp, thanks man! It works.

**Comment by isWill** [comment]
min and max cannot be equal  why?

**Comment by leongersen** [comment]
noUiSlider 15.4.0 adds support for sliders with ranges where min = max. In this case, handles are spaced evenly across the slider.

Thank you for your feedback, everybody!
