### ISSUE TITLE
ie11 on win7 doesn't add noUi-state-drag on handle drag

### ISSUE THREAD

**Issue by andy-hook** [leongersen/noUiSlider#435]
Hello,

I am using the state classes to style elements and noticed that in ie11 the state-drag class isn't applied when dragging a handle.

Any ideas?

**Comment by leongersen** [comment]
Looking at the source now... `noUi-state-drag` is used to force the `default` cursor (instead of the text selection one). It [mistakenly assumes](https://github.com/leongersen/noUiSlider/blob/127be4f3758497cbeb962512c234ed40bf387810/src/js/scope_events.js#L101) this shouldn't happen when using pointer events. That `if` could just be removed, it is just there for performance reasons on phones.

**Comment by andy-hook** [comment]
I'd prefer to keep the condition to avoid the action on mobile devices if possible, I could substitute a modernizr.touch test but I wondered if there is a simpler way?

**Comment by leongersen** [comment]
noUiSlider does fairly specific event detection to support all the platforms that it does, so replacing it with modernizer is probably not a good idea. Adding pointer events [here](https://github.com/leongersen/noUiSlider/blob/127be4f3758497cbeb962512c234ed40bf387810/src/js/structure.js#L76) would do.

**Comment by andy-hook** [comment]
Great, thanks!
