### ISSUE TITLE
Consistent, draggable range with a non-linear stepped slider

### ISSUE THREAD

**Issue by samdobson** [leongersen/noUiSlider#438]
First and foremost, congratulations on a fantastic project.

I have a use case where the user should be able to drag a range always spanning two steps with a non-linear slider. Is this possible with the tool in its current state? Current setup (below) gives some funky behaviour when crossing range boundaries (one handle moving without the other, varying number of steps in range, and other anomalies).

```javascript
$("#slider").noUiSlider({
  connect: true,
  behaviour: 'drag-fixed',
  start: [ 50000, 70000 ],
  range: {
    'min': [    50000,   10000 ],
    '20%': [   100000,   10000 ],
    '40%': [   250000,   25000 ],
    '60%': [   500000,   50000 ],
    '80%': [  1000000,  250000 ],
    'max': [  4000000 ]
  },
});
```

**Comment by leongersen** [comment]
I forgot to answer this, sorry! Dragging across a multi-range slider with steps is inconsistent because the slider tries to keep the difference between the handles the same. It can't, though, when it needs to obey steps or range thresholds.

What exactly is your use case? Maybe there is a workaround.

For reference, your snippet:
http://jsfiddle.net/leongersen/cjgdxe0q/
