### ISSUE TITLE
Improve mobile performance via translate3D

### ISSUE THREAD

**Issue by andy-hook** [leongersen/noUiSlider#439]
Hello,

Have you considered implementing a "use hardware acceleration" option? currently performance is not great on mobile devices due to "left" / "top" thrashing the layout. This could be greatly improved though use of translate3D.

Thoughts?

**Comment by leongersen** [comment]
Yes, I'm currently porting noUiSlider to plain js, and I plan to drop IE7 & IE8, while keeping the current version as a backup option for those. IE9 supports 2d transforms [with the `-ms-` prefix](http://caniuse.com/#feat=transforms2d), so replacing `top` and `left` by transforms is definitely on the list.

**Comment by leongersen** [comment]
I ran some tests.

First: The `connect` option can't really be implemented using translates. The handles can be positioned by translating the `.noUi-origin` elements, although that would 'leak' them outside `.noUi-base`. Using any combination of `overflow` would clip handles within the slider.

Second: There don't seem to be very significant performance benefits. Sample times are slightly off (my bad), and I just moved a handle rapidly around. There is no significant change in 'painting' time. The slider itself is already forced on it's own layer. 

**Using `left`:**
![left](https://cloud.githubusercontent.com/assets/1206361/8249011/12b7de26-1666-11e5-9bd9-302906d4d68c.png)

**Using `transformX`:**
![translate](https://cloud.githubusercontent.com/assets/1206361/8249013/1671b942-1666-11e5-8729-36b0d9ded485.png)

**Comment by andy-hook** [comment]
If you kick the rendering on to the GPU using translate3d rather than a 2d translate I think you would see a significant improvement to render speed, especially on mobile devices. However, what you say is true and it's not that simple, plus you'd need to add the 2d translate fallback or double stack the props.

I still think it's a goal worth shooting for if you want that extra performance on mobile, would be interested to see a repeat test using translate3d if you have time and are still pursuing this improvement.

**Comment by leongersen** [comment]
I've spend a ton of time messing with this, most of it with a profiler. Some conclusions:
+ Implementing the `connect` option without an additional element is not possible when using `transform`;
+ `.noUi-origin` elements would have to have a width of `100%` to keep relative/responsive positioning working, which would cause the to flow out of the parent container. Setting any `overflow` value would clip handles.

I did, however, notice some performance issues. I'd always seen some in Internet Explorer, but with the way better developer tools in Edge I looked into it a lot closer. The problem was mainly in paint times: updating a handle position would take ~6ms and happen often enough to seem laggy. Chrome optimizes this itself. I've implemented a fix by using `requestAnimationFrame` to update the handle positions, and it has done wonders on responsiveness in Edge and some mobile browsers.

Here is the [implementation](https://github.com/leongersen/noUiSlider/blob/606ead30046e579237674c65ddab7cc9dfba9e0f/src/js/scope.js#L43). @andy-hook, thanks for thinking along! I'm open to any other performance improvements.
