### ISSUE TITLE
unsubscribe all events handlers on destroy

### ISSUE THREAD

**Issue by vvo** [leongersen/noUiSlider#612]
what do you think? It's currently not done I think

**Comment by leongersen** [comment]
I'm not making this the default, because I'm assuming the usual reason for destroying/updating is to *rebuild* the slider, and to use it again. If the slider isn't rebuild, the events won't fire so it doesn't matter. 

To accommodate this, I *did* add support for `slider.noUiSlider.off()` to remove all bound events.

**Comment by leongersen** [comment]
That change is in 8.4.0.
