### ISSUE TITLE
Slider don't update it's handles after set

### ISSUE THREAD

**Issue by fabiocaruso** [leongersen/noUiSlider#630]
I use noUiSlider in a firefox addon. I tried this to set the slider values:
`$("#slider").val([0, 100]);`
after that i output the values of the slider:
`console.log($("#slider").val());`
oiutput:
Array ["0","100"]
so it sets the values but the handles are in the same position as before. Tooltips are enabled and show me NaN:NaN:NaN. (the formatter formats it to HH:MM:SS)
creation and setting:
`noUiSlider.create(timeSlider, {
	start: [ 0 , 100],
	connect: true,
	behaviour: 'drag-tap',
	step: 1,
	range: {
		'min': [ 0 ],
		'max': [ 100 ]
	},
	tooltips: [ formatter, formatter ],
	format: formatter
});`
`self.port.on("duration", function(duration) {
	timeSlider.noUiSlider.updateOptions({
		range: {
			'min': 0,
			'max': duration
		}
	});
	$("#slider").val([0, 100]);
	console.log($("#slider").val());
});`

I tried also to set a margin correctly but after setting the margin to 1 in creation and updating the range max value to the duration value and the margin to 1 i can drag the handles and it stops by different values but not by 1. So i think the margin is also not updated. the values of the margin vary dependent on the max range value.

**Comment by leongersen** [comment]
You seem to be using various version of the slider and the documentation mixed together. `.val()` is the jQuery version, while `noUiSlider.create` is not. If you could clean up your example and post it to [stackOverflow](http://stackoverflow.com/questions/tagged/nouislider), as this is a support question rather than an issue with the library, that'd be good.
