### ISSUE TITLE
The min value of Pips display wrongly when the min value is between 0 and 1

### ISSUE THREAD

**Issue by yunjiali** [leongersen/noUiSlider#636]
I am using the angularjs directive defined [here](https://github.com/Yankovsky/nouislider-angular), which uses v8.1.0

When I try to initialise the slider with following options:

```
{
    start: 1,
    range: {'min': 0.5, 'max': 1},
    step: 0.01,
    pips:{
      mode:'range',
      density:10
    }
  };
```
The start value of pip is 1 instead of 0.5. I have also tried to change ```range.min``` to 0.4, then I got 0. If the ```range.min``` is an integer (such as 10), I didn't get this problem. Not sure if this has been fixed in the latest version? The test cases in addon_pips.js doesn't cover this situation I think.

**Comment by leongersen** [comment]
You got me worried I'd be in for some tough debugging, but I got lucky :)

The pips feature supports a `format` option. By default, the formatting function is set to [`Math.round`](https://github.com/leongersen/noUiSlider/blob/master/src/js/pips.js#L219). That's why you are seeing `0.5` as `1`.

The simplest solution is just passing a `noop` formatter:

```
pips:{
	mode: 'range',
	density: 10,
	format: { to: String }
}
```

**Comment by yunjiali** [comment]
@leongersen Fantastic. Thank you very much for your quick response 👍
