### ISSUE TITLE
Uncaught TypeError: Cannot read property 'nodeName' of null

### ISSUE THREAD

**Issue by brut0** [leongersen/noUiSlider#658]
I added this code after connecting .js of noUISlider
```
<script>
var handlesSlider = document.getElementById('slidertest');

noUiSlider.create(handlesSlider, {
	start: [ 4000, 8000 ],
	range: {
		'min': [  2000 ],
		'max': [ 10000 ]
	}
});
</script>
```
And I see this error

> Uncaught TypeError: Cannot read property 'nodeName' of null
> initialize	@	nouislider.js:1939

**Comment by leongersen** [comment]
Is `handlesSlider` `null`?

**Comment by nico66** [comment]
Use document ready or code script at the bottom. See the examples.. and http://stackoverflow.com/questions/9899372/pure-javascript-equivalent-to-jquerys-ready-how-to-call-a-function-when-the

**Comment by AlexandreLogist** [comment]
Same error.. can't get it working, even with document ready.

**Comment by leongersen** [comment]
This has **nothing** to do with `document.ready`. When you call `getElementById` (or any other method to select an element) that element does not exist (yet). This *may* be due to the document not having loaded, a typo in your selector, etc.

**Comment by AlexandreLogist** [comment]
Hello


thanks for the answer, it found the issue yesterday and solved it.


Greetings and have a nice weekend,


Met vriendelijke groet,

Alexandre Logist
Logist.alex@live.be
0494 59 31 31

[let op het milieu] Denk aan het milieu voordat u dit bericht print!


________________________________
Van: Leon Gersen <notifications@github.com>
Verzonden: vrijdag 19 mei 2017 8:55
Aan: leongersen/noUiSlider
CC: ALEX LOGIST; Comment
Onderwerp: Re: [leongersen/noUiSlider] Uncaught TypeError: Cannot read property 'nodeName' of null (#658)


This has nothing to do with document.ready. When you call getElementById (or any other method to select an element) that element does not exist (yet). This may be due to the document not having loaded, a typo in your selector, etc.

**Comment by Liphin** [comment]
indeed, please trigger the highchart after document has loaded completed. For example, when use angularjs , please initiate highchart in proper time

**Comment by NnarayanSsharma** [comment]
I still can't find solution of this problem, help me
