### ISSUE TITLE
input field inside tooltip

### ISSUE THREAD

**Issue by aivils** [leongersen/noUiSlider#659]
At this moment I can place &lt;input&gt; in the tooltip &lt;div&gt; but I cannot focus that input field with mouse click because mouse events are used by slider. I can focus that &lt;input&gt; with keyboard Tab key only.

I tried to bound external &lt;input&gt; to slider's handle movement but none of slider's events report correct position of handle. This example https://refreshless.com/nouislider/examples/#section-non-linear is broken. Reported position of handle is wrong. Reported position is before CSS-ed animation. Anybody can check example above mentioned  by moving handle and watching position. Seems incorrect handle's position reading is related to non linear slider animation.

So customer request editable tooltips  together with non linear slider and I am stuck.

**Comment by leongersen** [comment]
* You can manage this in-tooltip input using `stopPropagation()` so events never reach the handle.
* The example you point to is indeed incorrect, I forgot to update it. The fifth argument to the `update` callback contains the slider positions *after* animation, so that can be used. See the [documentation for that here](https://refreshless.com/nouislider/events-callbacks/#section-binding).

**Comment by aivils** [comment]
Unfortunately it is vice versa.
Events never reach in-tooltip &lt;input&gt;. Mouse events are handled by slider. Some of mouse events are necessary to focus a &lt;input&gt;.

**Comment by leongersen** [comment]
Can you set up a jsFiddle/jsBin/codePen etc to demonstrate what you are doing?

**Comment by aivils** [comment]
Okay,
https://jsfiddle.net/6oc2pqpz/1/
Tooltips has input where supposed site visitor to type values into.
However visitor cannot click to input to get the focus.
Instead visitor should click to HTML BODY then press Tab until it will focus input then type value
then slider updates handle .
This is an edge case as slider works as expected by my additions wil not work.

**Comment by leongersen** [comment]
Your code is very inefficient. Please **do not** create input element and attach events to the on *every* update event. This will cripple your application/website performance, especially on mobile devices.

I've updated your example, so that it creates the tooltips and inputs once, and updates the slider/input values when it needs to:

https://jsfiddle.net/leongersen/6oc2pqpz/2/

**Comment by aivils** [comment]
Awesome!
I was chained into the tooltip option. Now i am free.
My project has bunch of sliders. I add minor update in the example where everything is stored in the element. Just single JS variable exposed.
https://jsfiddle.net/6oc2pqpz/3/
I guess this conversation will help programmers of future.

**Comment by leongersen** [comment]
Lets hope it does! I'll add a link to the documentation.

**Comment by saratSubramaniam** [comment]
Latest version of noUiSlider supports more than 2 handles. And this option is not working for the third handle. Does anybody have any thoughts ?

**Comment by aivils** [comment]
I suppose it is hardcoded. Latest jsfidle have Leon comment "// An 0/1 indexed array of input elements".
May be adding makeTT(2, nonLinearSlider) it will add input element for 3rd handle.
Untouched https://jsfiddle.net/6oc2pqpz/3/

**Comment by saratSubramaniam** [comment]
You're right. Adding that would add the input box for the 3rd handle. But while sliding (update event fires), the input box value doesn't change.
