### ISSUE TITLE
Rounding issues for larger ranges

### ISSUE THREAD

**Issue by richardsweeney** [leongersen/noUiSlider#675]
For larger ranges (eg. 1 - 20 000) if the step is set to something other than 1 there are very often slight rounding errors in the values.

For example:

```
step: 100,
range: {
	min: 1,
	max: 20000
}
```

![noui](https://cloud.githubusercontent.com/assets/761071/17614476/efcf4196-6066-11e6-9ef4-18f4d2205f2e.png)

**Comment by leongersen** [comment]
Sorry for my delayed response:

The slider is worked as per the documentation here. It starts from `1`, stepping in increments of `100`. It looks a little odd due to `1` being the first value, but when the first value is, for example, `2050`, it is more sensible. You can use the `format` option and [`floor`/`ceil` the value to the nearest `100`](http://stackoverflow.com/questions/19621455/rounding-up-to-the-nearest-100-in-javascript) to achieve the effect I think you want.
