### ISSUE TITLE
different range for the handlers

### ISSUE THREAD

**Issue by kayazinc** [leongersen/noUiSlider#686]
Is it possible to have different range for different handler?  Example, 
- handle 1 (range 0-50)
- handle 2 (range 50-100)

```
noUiSlider.create(testSlider, {
    start: [25, 75],
    connect: true,
    range: {
        'min': [0, 50],
        'max': [50, 100]
    }
});
```

**Comment by leongersen** [comment]
Not currently. I like the idea, though.

**Comment by leongersen** [comment]
I'm closing this issue, as it is not a feature I intend to implement, there seems to be no additional interest beyond the initial request, and I'm trying to clear the issue tracker. If there is further interest in a feature like this, feel free to comment - I'll reopen this issue. I'm also open to pull requests.

**Comment by snolflake** [comment]
It was very surprising to me to see much more complex features implemented and not this one. Also I didn't found documentation about why `min` and `max` accept arrays not sure about what happens when I provide multiple values there.

In my case I need to disable only one handler but only in one direction. My solution is to set a custom margin every time a drag starts based on which handler is being dragged.

@leongersen Maybe the lack of interest is because everyone that needed it so far found an alternative way to achieve this behavior?  I didn't found anything about it but maybe there is an undocumented way to make additional validations before moving a handler to the next step and `return false` to keep it where it is?

Thanks for any help!

**Comment by leongersen** [comment]
There isn't currently a way to insert custom validation logic, but that is a different feature request (and one I'd consider) all together.
