### ISSUE TITLE
Pips position in vertical orientation

### ISSUE THREAD

**Issue by pizzetto** [leongersen/noUiSlider#716]
Hi guys, 

I have a 4 steps range vertical slider, everything works just fine except the pips position.
It seems somehow that every label is displayed one step below the main pip, an image will clarifies much better:
![uislider-1](https://cloud.githubusercontent.com/assets/20169558/19927889/3534393c-a0fc-11e6-8991-972c77dbb094.jpg)

here's my code:
```javascript
var date_slider = document.getElementById('date_slider');
        date_slider.style.height = '400px';
        date_slider.style.margin = '10px';
        noUiSlider.create(date_slider, {
            start: 12,
            step: 6,
            orientation: 'vertical',
            behaviour: 'tap',
            connect: [true, false],
            range: {
                'min': [6],
                'max': [24]
            },
            pips: { // Show a scale with the slider
		mode: 'values',
                values: [6, 12, 18, 24],
		density: 24,
		format: {
                    to: function ( value ) {
                        switch (value)   {
                            case 6:
                                return 'Mattina';
                                break;
                            case 12: 
                                return 'Pomeriggio';
                                break;
                            case 18: 
                                return 'Sera';
                                break;
                            case 24:
                                return 'Notte';
                                break;
                        }
                    },
                    from: function ( value ) {
                        switch (value)   {
                            case 'Mattina':
                                return 6;
                                break;
                            case 'Pomeriggio': 
                                return 12;
                                break;
                            case 'Sera': 
                                return 18;
                                break;
                            case 'Notte':
                                return 24;
                                break;
                        }
                    }
                }
            }
        });
```

The label seems to be placed in a different `div` rather than the `div` containing the pips

**Comment by flibX0r** [comment]
This is an issue that I've just hit as well. It's not the wrong pips being selected, it's that the base stylesheet has the same transformation for both LTR and RTL labels, which beings at least one of them is broken in each orientation. It's visible in the examples:

![Example of styling issue](http://i.imgur.com/HvTo5RQ.png)

The cause is the CSS transform used to center the labels. It used to be -50%, it changed to +50% in 4188e4c82aa025fcaaa87a0f7d32d7351d48e544. The value needs to be different depending on whether the slider is LTR or RTL, as the pips are created from different directions using absolute positions but the transform directions are always left-to-right, top-to-bottom.

I've resolved the issue locally, I'll create a pull request.
