### ISSUE TITLE
slider's z-index

### ISSUE THREAD

**Issue by NipBoss** [leongersen/noUiSlider#829]
It appears on top of everything in the page even when given a negative z-index, how to fix this? I have a pop-up box opening on my site and I wish to disply text in the box but the slider is in the way.
How can I fix this?

**Comment by nicknack23** [comment]
Have you checked the CSS definitions in the source? There you can see that `.noUi-base` and `.noUi-handle` have a default z-index of 1. So just set a higher z-index for your pop-up box and it should appear on top of the slider. I tested it and it works for me.

**Comment by NipBoss** [comment]
Yea, I changed those to -1 and my pop-up to 1, it's still above the pop-up and im confused.
check out my site www.ubit.ca, when you click the 'View Keys' button.
the style.css and nouislider.css are in the css folder www.ubit.ca/css

**Comment by nicknack23** [comment]
I meant add a higher z-index for your pop-up box INSTEAD of setting a negative z-index for the slider. Everything seems fine if you do it my way, see [screenshot](https://imgur.com/a/Q6Eao). The slider works if you disable the negative z-index and the popup is on top of the slider (I just moved it with devtools).

**Comment by NipBoss** [comment]
The pop-up i'm talking about is the one that you open when you click "view keys", im trying right now, let me see.
