### ISSUE TITLE
Range like 000, 001, 002 ... 240, 252, 264

### ISSUE THREAD

**Issue by alturic** [leongersen/noUiSlider#914]
I'm wondering if there's a way to have a slider range like:

000,
001,
002
...
240
252
264

Basically increment by 1, up to a certain number (not percent) and then increment differently.

Same would go for:

000,
003
006,
...
048,
054,
060
...
240,
252,
264

This would increment by 3, up to a certain number and then by 6, and then finally by 12.

**Comment by leongersen** [comment]
Yes, it is! You are looking for this setting:

https://refreshless.com/nouislider/slider-values/#section-non-linear-step

**Comment by truewx** [comment]
Hmm do the % values actually mean something, outside of the display aspect of where to put the “beginning” number of the range?

For example, I have a slider with a “start” of 1. I have the range

“min”: 1,
“20%”: [24, 3],
“50%”: [240, 12],
“max”: 384

And it does go by 1 until 24, then it does go to 27, but then it goes to 29, not 30?

**Comment by truewx** [comment]
I got it, it was the format I was using causing it oddly.

Is there really not a way to pass the range a numerically indexed array and have it increment for each key like:

[0] => 0,
[1] => 1,
[2] => 240,
[3] => 252

Each step would be incrementing by 1 (the key) and youd have the value of the key. The min, max and inbetween steps are a nightmare to setup for the all the different increments I have. Im going to look at the html input way of trying it tommorow and see if it works how I’d need. I really need a way to insert an arbitrary amount of steps (array would be easiest) and have it almost automatically know the increments based on what was passed in.

**Comment by leongersen** [comment]
You could write a single loop, iterating over that array, that generates the percentages for you.

```
let out = {};
let length = ranges.length;

// pseudo code
ranges.forEach(range, index => {
    out[((100 / length) * index) + '%'] = range;
});
```

There is some discussion on a 'range builder' here: #898

**Comment by truewx** [comment]
So, I got the slider working. Now, I'm confused on how to increment/decrement using a +/- button. Not really how to get it to work, but how to get the next "step". For example, I'm incrementing great when it's, 1, 2, 3, 4, 5 but when it gets to 24, the next step is 27, so it just keeps trying to increment to a defunct 25 (I guess).

Doing slider.noUiSlider.steps() doesn't return anything but false or null. On hour 24, it's false, false since it CAN actually increment but I need to get what the next increment/number actually is.

**Comment by leongersen** [comment]
In the steps method, `false` is "no step set", `null` is "at slider edge". Could you show some code?

**Comment by truewx** [comment]
Very interesting. When it's at min, .steps() shows [null, false]. Then at max is shows [false, null]. So that is technically "working" that it knows if there's a future/past step. When it's on a step that's not the min or max, it shows [false, false], again knowing there is a future/past step available.

My setup is basically this: https://refreshless.com/nouislider/examples/#section-huge-numbers with the only exception being the range var with the min/max/percents, I'm using directly on range: range,

**Comment by leongersen** [comment]
To confirm, does your range contain steps?

```
	range: {
		'min': [0], // step would be false
		'10%': [10, 10], // step would be 10
		'50%': [80, 50], // step would be 50
		'80%': 150, // step would be false
		'max': 200
	}
```

**Comment by truewx** [comment]
No sir, it's structured exactly like that example.

**Comment by leongersen** [comment]
Ah, ok. If there's no steps in your range, the `steps` api will always have `false` for the step value. If you show me some code I can give you some pointers.

**Comment by alturic** [comment]
That is correct, there's no steps. it's the range, like we mentioned above.

Is there anyway to *cough* "step" through the slider values? I'm looking to add a +/- button that will increment/decrement the slider.

**Comment by leongersen** [comment]
You might also be interested in the [snap option](https://refreshless.com/nouislider/slider-values/#section-snap).

**Comment by leongersen** [comment]
Closing this as I assume the question is answered. Feel free to comment.
